hmcts/finrem-ccd-definitions

definitions/consented/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json, definitions/consented/json/AuthorisationCaseState/AuthorisationCaseState.json, definitions/consented/json/CaseEvent.json, definitions/consented/json/State.json
https://tools.hmcts.net/jira/browse/RPET-143
=> RPET-143: Caseworker ability to move cases into an Awaiting Information State

definitions/consented/json/AuthorisationCaseField/AuthorisationCaseField-nonprod.json, definitions/consented/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/consented/json/CaseEventToFields/CaseEventToFields-nonprod.json, definitions/consented/json/CaseEventToFields/CaseEventToFields.json, definitions/consented/json/FixedLists/FixedLists.json, definitions/consented/json/FixedLists/FixedLists_FR_fl_StageReached-nonprod.json, test/unit/definitions/consented/CaseEventToFields.test.js, test/unit/definitions/consented/GenericValidation.test.js, test/unit/definitions/consented/UserEventAuthorisation.test.js
We need to remove this option from prod.
=> toggle off BSP-356 (FR_fl_StageReached) and BSP-284 (divRoleOfFrApplicant)

README.md
Updating information about how to use CCD in AKS.
```
[ ] Yes
[ x ] No
```
=> Updating information about how to use CCD in AKS

definitions/consented/json/Banner.json, definitions/contested/json/Banner.json
https://tools.hmcts.net/jira/browse/RPET-223
```
[ ] Yes
[x] No
```
=> Rpet-223-take-down-performance-banner

definitions/contested/json/CaseEvent.json, package.json
=> Fr 1468 contest order notification

definitions/contested/json/CaseEvent.json, package.json
=> adding callback to prepare for hearing order sent to send notification

Jenkinsfile_CNP, charts/finrem-ccd-definitions/Chart.yaml, charts/finrem-ccd-definitions/requirements.yaml, charts/finrem-ccd-definitions/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/FR-1685
Use AAT document storage for uploaded docs
```
[ ] Yes
[ ] No
```
=> Fr 1685 ccd document upload

definitions/consented/json/AuthorisationCaseField/AuthorisationCaseField.json
Updated Court Admin privileges for 'DischargePeriodicalPaymentSubstituteFor' field from R -> CRU to allow court admins to transfer exception case to state 'new paper case'
=> FR_1687: Updated permissions for DischargePeriodicalPaymentSubstituteFor field

definitions/consented/json/AuthorisationCaseField/AuthorisationCaseField-nonprod.json, definitions/consented/json/CaseField/CaseField-nonprod.json, definitions/consented/json/CaseTypeTab/CaseTypeTab-nonprod.json, package.json
=> FR-1664 & FR-1665 - removing consentOrderApprovedNotificationLetter document field

definitions/contested/json/AuthorisationCaseField.json, definitions/contested/json/CaseEventToFields.json, definitions/contested/json/CaseField.json, definitions/contested/json/CaseTypeTab.json
https://tools.hmcts.net/jira/browse/FR-1369
Additional information about hearing field
```
[ ] Yes
[ ] No
```
=> creating new additional info for hearing field

definitions/contested/json/AuthorisationCaseEvent.json, definitions/contested/json/AuthorisationCaseState.json
https://tools.hmcts.net/jira/browse/FR-1546
```
[ ] Yes
[ ] No
```
=> FR-1546 - adding create permission to judge for casenotes

definitions/consented/json/CaseRoles.json, definitions/contested/json/CaseRoles.json
https://tools.hmcts.net/jira/browse/FR-1695
Add case role for respondent and applicant solicitors
```
[ ] Yes
[ ] No
```
=> adding resp and app sol case roles

charts/finrem-ccd-definitions/requirements.yaml, definitions/consented/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/consented/json/CaseEventToFields/CaseEventToFields.json, definitions/consented/json/CaseField/CaseField.json, definitions/consented/json/CaseTypeTab/CaseTypeTab.json, definitions/contested/json/AuthorisationCaseField.json, definitions/contested/json/CaseEventToFields.json, definitions/contested/json/CaseField.json, definitions/contested/json/CaseTypeTab.json
https://tools.hmcts.net/jira/browse/FR-1599
Giving Caseworker permission to mark respondent address as confidential in UpdateContactDetails Event
```
[ ] Yes
[x] No
```
=> Adding confidential address question into Update Contact Details Events

definitions/consented/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
https://tools.hmcts.net/jira/browse/FR-1696
Remove migration permissions for users in production
```
[ ] Yes
[ ] No
```
=> Remove Case Migration Permissions from Production

charts/finrem-ccd-definitions/values.aat.template.yaml
=> add aad identity name

definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json, definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
https://tools.hmcts.net/jira/browse/FR-1593
adding permissions for judge to the general letter even in contested and its fields
```
[ ] Yes
[x] No
```
=> fr-1593: updating privileges so judge can access contested general letter

charts/finrem-ccd-definitions/values.aat.template.yaml
=> Fix staging build failing

definitions/consented/json/CaseField/CaseField.json
https://tools.hmcts.net/jira/browse/FR-1754
Change wording on CCD
```
[ ] Yes
[x] No
```
=> FR-1754: General Order Update

definitions/consented/json/CaseEvent.json, package.json
https://tools.hmcts.net/jira/browse/FR-1566
add assign to judge callback to issue application events and update issue application end state
```
[ ] Yes
[ ] No
```
=> FR-1566: add assign to judge callback to issue application events

test/data/ccd-consented-case-worker-issue-data.json, test/data/ccd-contested-case-worker-issue-data.json, test/functional/consented_test.js, test/functional/contested_test.js
Contested and Consented cases allocated to judge
=> FR-1769 Added tests for allocating cases to judge

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/contested/json/CaseEvent/CaseEvent.json, definitions/contested/json/CaseEventToFields/CaseEventToFields.json, definitions/contested/json/CaseField/CaseField.json, definitions/contested/json/CaseTypeTab/CaseTypeTab.json, definitions/contested/json/ComplexTypes/ComplexTypes.json, definitions/contested/json/FixedLists/FixedLists.json, package.json
https://tools.hmcts.net/jira/browse/FR-1649
Contested Draft Order Not Approved / Refusal Order
```
[x] Yes
[] No
```
=> FR-1649: Contested Draft Order Not Approved

Jenkinsfile_CNP, Jenkinsfile_nightly, test/data/ccd-contested-to-consented.json, test/functional/codecept.conf.js, test/functional/consented_test.js, test/functional/contested_test.js, test/functional/pages/common/common.js, test/functional/pages/create-case/create-case.js, test/functional/steps_file.js
Added consented -contested tests
Initiated solicitor test for nightly using CCD UI screens
=> added more tests and solicitor create case test initiated for nightly build

Jenkinsfile_CNP
+ Add userprofile-consented-judgedetails-3 to jenkins file
```
[ ] Yes
[ ] No
```
=> RPET-327: Need to add new judges to consented

test/data/verify-tab-data.json, test/functional/consented_test.js, test/functional/pages/case-authorisation/case-authorisation.js, test/functional/pages/tab-data-verification/consented-tab-data-verification.js, test/functional/steps_file.js
once case submitted  by solicitor verify few details under each tab
=> FR-1769 tab data verification after solicitor submit case

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/contested/json/CaseEvent/CaseEvent.json, package.json
https://tools.hmcts.net/jira/browse/FR-1584
adding call to COS endpoint to send email on approval
```
[ ] Yes
[x] No
```
=> FR-1584: adding call to notify endpoint for general order consent in contested

definitions/consented/json/CaseEvent/CaseEvent-nonprod.json, definitions/consented/json/CaseEvent/CaseEvent-prod.json, definitions/consented/json/CaseEvent/CaseEvent.json
toggle on automated states in PROD
```
[ ] Yes
[ ] No
```
=> toggle on automated states in PROD

charts/finrem-ccd-definitions/values.preview.template.yaml
=> add print service to PR pods

definitions/contested/json/CaseTypeTab/CaseTypeTab.json, package.json
=> FR-1487: Bulk print docs

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField-nonprod.json, definitions/contested/json/CaseEvent/CaseEvent-prod.json, definitions/contested/json/CaseEvent/CaseEvent.json, definitions/contested/json/CaseField/CaseField-nonprod.json, definitions/contested/json/CaseTypeTab/CaseTypeTab-nonprod.json, definitions/contested/json/ComplexTypes/ComplexTypes-nonprod.json, definitions/contested/json/FixedLists/FixedLists-nonprod.json, definitions/contested/json/FixedLists/FixedLists-prod.json, definitions/contested/json/FixedLists/FixedLists.json, package.json, test/unit/definitions/contested/CaseEventToFields.test.js
https://tools.hmcts.net/jira/browse/FR-1545
FR-1545: Upload case document for applicant / respondent to the respective case documents tab
```
[x] Yes
[ ] No
```
=> FR-1545: Upload case document for specified party

Jenkinsfile_CNP, package.json, yarn.lock
+ Add more judges, due to this being greater than 25k characters, it need additional env variables
https://tools.hmcts.net/jira/browse/RPET-404
Added addtional env variables to handle extra azure secrets for judges
```
[ ] Yes
[ ] No
```
=> RPET-404: Add additional variables for judges

definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json, definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState.json, definitions/contested/json/CaseEvent/CaseEvent.json, definitions/contested/json/CaseEventToFields/CaseEventToFields.json, definitions/contested/json/CaseField/CaseField.json, definitions/contested/json/State/State.json, package.json
https://tools.hmcts.net/jira/browse/FR-1805
General application refer to judge
```
[ ] Yes
[ ] No
```
=> FR-1805: General application refer to judge

test/data/ccd-contested-general-applicaition.json, test/data/verify-contested-tab-data.json, test/functional/contested_test.js, test/functional/pages/tab-data-verification/tab-data-verification.js
verify general application tab data in nightly
=> Create general application test

test/data/verify-contested-tab-data.json
=> fix failed test on nightly

definitions/contested/json/FixedLists/FixedLists.json
https://tools.hmcts.net/jira/browse/FR-1816
Adding Allocation Questionnaire to 'Additional Documents' List
```
[ ] Yes
[x] No
```
=> Adding Allocation Questionnaire to 'Additional Documents' List

definitions/consented/json/WorkBasketResultFields.json, definitions/contested/json/WorkBasketResultFields/WorkBasketResultFields.json
https://tools.hmcts.net/jira/browse/RPET-413
add filtering to the workbasket results page to show older cases first
```
[ ] Yes
[x] No
```
=> Rpet 413 filter workbasket by lastmodified

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
https://tools.hmcts.net/jira/browse/FR-1832
adding in missing permissions for outcome and outcome other for general aplication.
```
[ ] Yes
[x] No
```
=> FR-1832: adding solicitor permissions for generalApplicationOutcome and other

charts/finrem-ccd-definitions/values.preview.template.yaml, package.json
Keyvault fix
```
[ ] Yes
[ ] No
```
=> Keyvault fix

definitions/contested/json/CaseEvent/CaseEvent.json
reverting callback type as cases we not populating
```
[ ] Yes
[x] No
```
=> reverting callback type to submit for paper case

definitions/consented/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/consented/json/CaseEvent/CaseEvent.json, definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/contested/json/CaseEvent/CaseEvent.json, package.json
https://tools.hmcts.net/jira/browse/FR-1813
General order email
```
[ ] Yes
[ ] No
```
=> FR-1813: General order email

definitions/contested/json/CaseEvent/CaseEvent.json, package.json
=> Fr 1761 awaiting judicary response notification

test/data/ccd-demo-contested-paper-case-basic-data.json, test/data/ccd-demo-contested-to-consented.json, test/functional/contested_test.js
API tests for consent in contested 
paper case in demo env
=> add consent-in-contested and paper case tests.

charts/finrem-ccd-definitions/Chart.yaml, charts/finrem-ccd-definitions/requirements.yaml, charts/finrem-ccd-definitions/values.aat.template.yaml, charts/finrem-ccd-definitions/values.preview.template.yaml, charts/finrem-ccd-definitions/values.yaml
=> disable idam pr in aat

Jenkinsfile_CNP, Jenkinsfile_nightly, test/functional/consented_test.js, test/functional/contested_test.js, test/functional/pages/create-case/create-case.js, test/functional/pages/solicitor-create/solicitor-create.js
run tests on nightly and master on XUI Web interface.
=> run tests on XUI aat

Jenkinsfile_CNP, Jenkinsfile_nightly, test/data/ccd-contested-allocation-directions.json, test/data/ccd-contested-list-for-hearing.json, test/data/verify-contested-tab-data.json, test/functional/contested_test.js, test/functional/pages/tab-data-verification/tab-data-verification.js
ready for hearing contested test
=> Add contested ready for hearing test

Jenkinsfile_CNP, Jenkinsfile_nightly, test/functional/contested-respondent_test.js, test/functional/pages/org-assign-cases/org-assign-cases-to-respondent.js, test/functional/steps_file.js
Create Contested case
Login as CAA
Assign it to respondent
=> create contested case

definitions/consented/json/AuthorisationComplexType/AuthorisationComplexType-respSol-nonprod.json, definitions/consented/json/AuthorisationComplexType/AuthorisationComplexType-shareAcase-nonprod.json, definitions/consented/json/CaseEventToComplexTypes/CaseEventToComplexTypes-respSolJourney-nonprod.json, definitions/consented/json/CaseEventToComplexTypes/CaseEventToComplexTypes-shareAcase-nonprod.json, definitions/contested/json/AuthorisationComplexType/AuthorisationComplexType-respSol-nonprod.json, definitions/contested/json/AuthorisationComplexType/AuthorisationComplexType-shareAcase-nonprod.json, definitions/contested/json/CaseEventToComplexTypes/CaseEventToComplexTypes-respSolJourney-nonprod.json, definitions/contested/json/CaseEventToComplexTypes/CaseEventToComplexTypes-shareAcase-nonprod.json, test/data/ccd-demo-consented-basic-data.json, test/data/ccd-demo-contested-basic-data.json, test/functional/pages/respondent-details/respondent-details.js, test/functional/pages/solicitor-create/solicitor-create.js
=> remove org name to fix master build

definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json, definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/contested/json/CaseEvent/CaseEvent.json, definitions/contested/json/CaseEventToComplexTypes/CaseEventToComplexTypes.json, definitions/contested/json/CaseEventToFields/CaseEventToFields.json
https://tools.hmcts.net/jira/browse/FR-1789
Amend final order Consent in Contested
```
[ ] Yes
[ ] No
```
=> FR-1789: Amend final order Consent in Contested

definitions/consented/json/WorkBasketInputFields.json, definitions/contested/json/WorkBasketInputFields/WorkBasketInputFields.json
https://tools.hmcts.net/jira/browse/RPET-542
This PR is for adding the court list filters on `Case List` and `Search` pages for consented and the contested cases
```
[ ] Yes
[X] No
```
=> RPET-542 Add court filters to case list page

definitions/consented/json/ComplexTypes.json, definitions/contested/json/ComplexTypes/ComplexTypes.json, package.json
https://tools.hmcts.net/jira/browse/FR-1901
```
[ ] Yes
[x] No
```
=> FR-1901: update labels

definitions/contested/json/CaseEvent/CaseEvent.json
https://tools.hmcts.net/jira/browse/FR-1912
Changed post state of FR_generalOrderConsent from consentOrderNotApproved to consentedOrderNotApproved
=> FR-1912: Changed post state of FR_generalOrderConsent to consentedOrderNotApproved

Jenkinsfile_CNP
=> RPET-631: Update Jenkins_CNP to handle new judge details secret

charts/finrem-ccd-definitions/Chart.yaml, charts/finrem-ccd-definitions/values.preview.template.yaml
=> specific xui version

definitions/consented/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
https://tools.hmcts.net/jira/browse/RPET-402
Update judge role so judges can see scanned documents
```
[ ] Yes
[x] No
```
=> RPET-402: Update Judge role to see scanned documents

definitions/consented/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
Reverts hmcts/finrem-ccd-definitions#328
Reverting to avoid this being released before it's approved by RM (I believe backlog team is doing a release monday morning)
=> Revert "RPET-402: Update Judge role to see scanned documents"

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RPET-649
- Update pipeline file to handle new fixed list and user profile secrets on azure
```
[ ] Yes
[x] No
```
=> RPET-649: Update jenkins pipeline to handle new judge secrets

definitions/consented/json/CaseEvent/CaseEvent.json, package.json
https://tools.hmcts.net/jira/browse/FR-1917
respondent order available email
```
[ ] Yes
[ ] No
```
=> FR-1917: respondent order available email

charts/finrem-ccd-definitions/values.preview.template.yaml, package.json, yarn.lock
- axios upgraded to `0.21.1`
- XUI image updated to `latest` instead of a specific version (the version it was pointing to was removed)
```
[ ] Yes
[x] No
```
=> Fixing lib vulnerability and stale XUI image

test/functional/pages/payment-page/payment-page.js, test/functional/pages/solicitor-create/solicitor-create.js, test/functional/pages/tab-data-verification/tab-data-verification.js
fix paper case tab selection test.
=> fix tests failed by increasing wait text time.

test/data/ccd-demo-contested-basic-data.json, test/functional/pages/org-assign-cases/org-assign-cases-to-respondent.js
**Note:** We can't run this test on pipeline- as there is active directory issue on Demo.
We can run from local pointing to Demo and authenticating with credentials manually.
We will enable this on AAT and pipeline once XUI enables share case for CAA Role.
=> fixing demo share case with respondent test

definitions/consented/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json, definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
- Removing Respondent Organisation Policy from Contested Cases
=> Toggle off /migrate in Consented, Enable in Contested

definitions/consented/json/AuthorisationCaseEvent/AuthorisationCaseEvent-respSol-nonprod.json, definitions/consented/json/AuthorisationCaseField/AuthorisationCaseField-respSol-nonprod.json, definitions/consented/json/CaseEvent/CaseEvent-respSol-nonprod.json, definitions/consented/json/CaseEventToFields/CaseEventToFields-respSol-nonprod.json, definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent-respSol-nonprod.json
https://tools.hmcts.net/jira/browse/FR-1931
RespSol can change their email 
```
[ ] Yes
[ ] No
```
=> FR-1931 RespSol edit their email address

definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
https://tools.hmcts.net/jira/browse/FR-1960
Toggle migration event off in prod
(Consented is already diasbled)
=> FR-1960: Toggle migration event off

definitions/consented/json/CaseEventToFields/CaseEventToFields-respSol-nonprod.json
https://tools.hmcts.net/jira/browse/FR-1933
Org Policy removal
```
[ ] Yes
[ ] No
```
=> FR-1933 consent confidential details

charts/finrem-ccd-definitions/Chart.yaml, charts/finrem-ccd-definitions/values.preview.template.yaml
=> Disabling app insights

charts/finrem-ccd-definitions/values.preview.template.yaml
=> Temporarily disable AppInsights for CCD web

charts/finrem-ccd-definitions/Chart.yaml, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/FR-1984
Updates base chart to latest version
```
[ ] Yes
[x] No
```
=> Update base chart to latest version

Jenkinsfile_CNP, definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json, definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/contested/json/CaseEvent/CaseEvent.json, definitions/contested/json/CaseEventToFields/CaseEventToFields.json, definitions/contested/json/CaseField/CaseField.json, definitions/contested/json/CaseTypeTab/CaseTypeTab.json, definitions/contested/json/FixedLists/FixedLists-nonprod.json, definitions/contested/json/WorkBasketInputFields/WorkBasketInputFields.json, definitions/contested/json/WorkBasketResultFields/WorkBasketResultFields.json, package.json
https://tools.hmcts.net/jira/browse/FR-1978
- Adding "Reserve for Judge" Event
- Dropdown populated from Azure Secrets
- Visible to only Caseworker and a Judge
- Stored on Admin Notes Tab
- Judge Name is visible on WorkBasket View
```
[ ] Yes
[x] No
```
=> Adding Reserve for Judge Event

package.json
=> Revert change FR1963

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/FR-1978
- Dont default users workbasket configurations for contested
```
[ ] Yes
[x] No
```
=> Remove UserProfile for Contested

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RPET-704
Sub task
https://tools.hmcts.net/jira/browse/RPET-781
```
[ ] Yes
[x] No
```
=> Add new keys for fixed-list of judges details.

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
https://tools.hmcts.net/jira/browse/FR-1993
- Adding permissions for Judge and Solicitors to view "generalApplicationDirectionsDocument" field
```
[ ] Yes
[x] No
```
=> Update permissions on General Application Directions Document field

package.json
=> Point AAT at AAT pod

Jenkinsfile_CNP
=> revert rpet 704

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RPET-704
Add new keys for fixed lists.
```
[ ] Yes
[x] No
```
=> Add new keys for consented and contested fixed list.

Jenkinsfile_nightly, test/functional/contested-respondent_test.js, test/functional/pages/org-assign-cases/org-assign-cases-to-respondent.js
enable share case for respondent side.
=> Enable share respondent nightly test

definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState-respSol-nonprod.json
If we remove authorisation on case roles for IDAM solicitor role then legacy cases will lose auth on these states, to prevent this we will leave the existing permissions of IDAM role on case states
```
[ ] Yes
[ ] No
```
=> Leave IDAM solicitor permissions on case states to support legacy cases

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RPET-829
```
[ ] Yes
[ ] No
```
=> Revert secret to previous release

definitions/consented/json/CaseEvent/CaseEvent.json, definitions/contested/json/CaseEvent/CaseEvent.json
https://tools.hmcts.net/jira/browse/RPET-911
- Standardise case submission callbacks for Consented and Contested
```
[ ] Yes
[x] No
```
=> INC5183093: Standardise case submission callbacks

definitions/contested/json/SearchInputFields/SearchInputFields.json
https://tools.hmcts.net/jira/browse/RPET-858
- Adding Divorce Case Number as a search option for Contested Config
```
[ ] Yes
[x] No
```
=> RPET-858: Adding Divorce Case Number to search for Contested

definitions/contested/json/CaseTypeTab/CaseTypeTab-nonprod.json, definitions/contested/json/CaseTypeTab/CaseTypeTab.json
- Move generalLetterCollection to `Case Documents` Tab in Contested
=> Move generalLetterCollection to CaseDocuments Tab

test/data/ccd-contested-caseworker-upload-order.json, test/data/ccd-contested-judge-approved.json, test/data/ccd-contested-solicitor-draft-direction-order.json, test/data/ccd-contested-solicitor-draft-order.json, test/data/verify-contested-tab-data.json, test/functional/contested_test.js, test/functional/pages/tab-data-verification/tab-data-verification.js, test/functional/steps_file.js
send order
document generation check
=> E2E test to check Contested judge approval

charts/finrem-ccd-definitions/Chart.yaml
=> Bumping CCD Chart to 5.0.2

Jenkinsfile_CNP, Jenkinsfile_nightly, test/functional/pages/check-your-answers/check-your-answers.js, test/functional/pages/divorce-details/divorce-details.js
format and waits for cross browser failures
=> Increase wait time for intermittent failures on cross browser.

definitions/consented/json/AuthorisationCaseState/AuthorisationCaseState.json, definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState.json, test/unit/definitions/consented/UserRoleStateAuth.test.js, test/unit/definitions/contested/UserRoleStateAuth.test.js
https://tools.hmcts.net/jira/browse/RPET-980
=> RPET-980: removed permissions from caa idam role 

README.md, definitions/consented/json/AuthorisationCaseState/AuthorisationCaseState.json, definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState.json, test/unit/definitions/consented/UserEventAuthorisation.test.js, test/unit/definitions/consented/UserRoleStateAuth.test.js, test/unit/definitions/contested/UserRoleStateAuth.test.js
https://tools.hmcts.net/jira/browse/RPET-992
=> RPET-992: Update state permissions for CAA and solicitor roles

README.md
https://tools.hmcts.net/jira/browse/DFR-40
- Adding new judges to list
- Updating labels
```
[ ] Yes
[x] No
```
=> DFR-40: Adding new judges to list and updating labels

Jenkinsfile_CNP, README.md
https://tools.hmcts.net/jira/browse/DFR-40
Adding judge details fixed list 6 to Jenkins build
```
[ ] Yes
[x] No
```
=> Dfr 40 update judge list

Jenkinsfile_CNP, README.md
https://tools.hmcts.net/jira/browse/DFR-40
- Removing duplications from judge list
```
[ ] Yes
[X] No
```
=> DFR-40: update judge list

README.md, charts/finrem-ccd-definitions/Chart.yaml
https://tools.hmcts.net/jira/browse/DFR-148
Add 44 new judges
```
[ ] Yes
[x] No
```
=> DFR-148: Update documentation to help track judge list change history

README.md
DFR-500: Update DJ list
Update list of judges
https://tools.hmcts.net/jira/browse/DFR-500
```
[ ] Yes
[x] No
```
=> DFR-500: Update DJ list

Jenkinsfile_nightly, test/functional/pages/create-case/create-case.js
https://tools.hmcts.net/jira/browse/DFR-597
- Fix the failing tests
```
[ ] Yes
[x] No
```
=> DFR-597 - Fix nightly pipeline

README.md
https://tools.hmcts.net/jira/browse/DFR-105
=> DFR-105 Add Judges

definitions/consented/json/CaseEventToComplexTypes/CaseEventToComplexTypes.json, definitions/contested/json/CaseEventToComplexTypes/CaseEventToComplexTypes.json
https://tools.hmcts.net/jira/browse/DFR-428
=> DFR-428 respondent organisation search issue

README.md, definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json, definitions/contested/json/CaseEvent/CaseEvent.json
https://tools.hmcts.net/jira/browse/DFR-535
=> DFR-535 Case needs to revert to prepareForHearing state

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
https://tools.hmcts.net/jira/browse/DFR-510
=> DFR-510 Solicitor view of scheduling & listing tab incomplete

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
https://tools.hmcts.net/jira/browse/DFR-606
Update Judiciary permission. 
```
[ ] Yes
[ ] No
```
=> Update permission judiciary

definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json, definitions/contested/json/CaseEvent/CaseEvent.json
https://tools.hmcts.net/jira/browse/DFR-560
=> DFR-560 Case needs to revert to submitted state

README.md, charts/finrem-ccd-definitions/values.preview.template.yaml, definitions/consented/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
https://tools.hmcts.net/jira/browse/DFR-380
Remove solicitor access to view general emails in the Case Documents tab
```
[ ] Yes
[x] No
```
=> DFR-380: Remove solicitor access to general emails

package.json, yarn.lock
DFR-854
Upgrade properties-volume for finrem-ccd-defintions
```
[ ] Yes
[x] No
```
=> DFR-854: Upgrade properties-volume for finrem-ccd-defintions

charts/finrem-ccd-definitions/Chart.yaml
=> bump node chart version

README.md
https://tools.hmcts.net/jira/browse/DFR-529
Created a dummy PR to leave a milestone for the updated judges.
```
[ ] Yes
[x] No
```
=> DFR-529 dummy pr updating judges

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/DFR-529
DFR-529 update jenkinsfile_cnp to include judge details 7 and 8
```
[ ] Yes
[x] No
```
=> DFR-529 update jenkinsfile_cnp to include judge details 7 and 8

README.md
=> update ReadMe with Mac M1 chip setup

charts/finrem-ccd-definitions/Chart.yaml, charts/finrem-ccd-definitions/values.yaml
=> fix values.yaml

README.md
https://tools.hmcts.net/jira/browse/dfr-529
Update  fixed list.
```
[ ] Yes
[x] No
```
=> DFR-529 update fixed list

package.json, test/functional/consented_test.js, test/functional/contested_test.js, test/functional/pages/saving-application-information/saving-application-information.js
https://tools.hmcts.net/jira/browse/DFR-915
=> DFR-915 Fix nightly build

README.md
https://tools.hmcts.net/jira/browse/DFR-529
```
[ ] Yes
[ ] No
```
=> added more judges

definitions/contested/json/CaseEvent/CaseEvent.json
https://tools.hmcts.net/jira/browse/DFR-790
```
[ ] Yes
[ ] No
```
=> DFR-790-update precondition states

definitions/contested/json/CaseEvent/CaseEvent.json
DFR-790
Added missing state prepareForHearing
```
[ ] Yes
[x] No
```
=> DFR-790: added missing state

definitions/consented/json/AuthorisationCaseField/AuthorisationCaseField-nonprod.json, definitions/consented/json/CaseField/CaseField-nonprod.json, definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField-nonprod.json, definitions/contested/json/CaseField/CaseField-nonprod.json
Addition of Change Organisation Request case field to non-prod envs in preparation for upcoming NoC tickets
```
[ ] Yes
[ ] No
```
=> DFR-891: add changeOrganisationRequest Field nonprod

package.json, yarn.lock
=> update moment Dependnecy

definitions/contested/json/FixedLists/FixedLists.json
https://tools.hmcts.net/jira/browse/DFR-877
[FR 2022] - Maintenance Pending Suit - Update existing fixed lists for uploading document events, with new values
```
[ ] Yes
[x] No
```
=> DFR-877: Maintenance Pending Suit - Update existing fixed lists

definitions/consented/json/FixedLists/FixedLists.json, definitions/contested/json/FixedLists/FixedLists.json, test/data/ccd-consented-basic-data.json, test/data/ccd-contested-basic-data.json, test/data/verify-consented-tab-data.json, test/data/verify-contested-paper-case-tab-data.json, test/data/verify-contested-tab-data.json, test/functional/pages/nature-of-application/nature-of-application.js, test/functional/pages/saving-application-information/saving-application-information.js, test/functional/pages/tab-data-verification/tab-data-verification.js
Dfr 876 mps nature application
=> Dfr 876 mps nature application

definitions/contested/json/CaseEventToComplexTypes/CaseEventToComplexTypes.json, test/unit/definitions/contested/CaseTypeTab.test.js
=> Dfr 879 fix dupe case event id

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/contested/json/CaseField/CaseField.json, definitions/contested/json/CaseTypeTab/CaseTypeTab.json, definitions/contested/json/ComplexTypes/ComplexTypes.json, package.json, yarn.lock
[https://tools.hmcts.net/jira/browse/DFR-983](url)
```
[ ] Yes
[ ] No
```
=> DFR-983: Fix dupe issue with Upload Order

README.md, definitions/contested/json/CaseField/CaseField.json
=> DFR-924 change for draft general app doc

Jenkinsfile_CNP
Prevent pod cleanup by adding no_cleanup label to github repo
=> Prevent cleanup with no_cleanup label

charts/finrem-ccd-definitions/values.preview.template.yaml, definitions/consented/json/AuthorisationCaseState/AuthorisationCaseState.json, definitions/consented/json/CaseEvent/CaseEvent.json, definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState.json, definitions/contested/json/CaseEvent/CaseEvent.json
https://tools.hmcts.net/jira/browse/DFR-1073
Fix for change in unassigned case list behaviour showing too many cases
```
[ ] Yes
[x] No
```
=> DFR-1073-fix unassigned bug

Jenkinsfile_CNP, README.md
https://tools.hmcts.net/jira/browse/DFR-1086
=> DFR-1086 Configure Pipeline for Additional Tests

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
https://tools.hmcts.net/jira/browse/DFR-993
Amended Field permissions
```
[ ] Yes
[x] No
```
=> DFR-993: amended case field permissions

definitions/consented/json/AuthorisationCaseState/AuthorisationCaseState-DFR-734-nonprod.json, definitions/consented/json/AuthorisationCaseType/AuthorisationCaseType-DFR-734-nonprod.json, definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent-DFR-734-nonprod.json, definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState-DFR-734-nonprod.json, definitions/contested/json/AuthorisationCaseType/AuthorisationCaseType-DFR-734-nonprod.json, test/functional/admin_test.js
https://tools.hmcts.net/jira/browse/DFR-734
Change superuser rolename upon request with ccd
```
[ ] Yes
[x] No
```
=> DFR-734 - update superuser Role name

definitions/consented/json/AuthorisationCaseEvent/AuthorisationCaseEvent-DFR-1093-UpdateOrg-nonprod.json, definitions/consented/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json, definitions/consented/json/CaseEvent/CaseEvent.json, definitions/consented/json/CaseEventToComplexTypes/CaseEventToComplexTypes.json, definitions/consented/json/CaseEventToFields/CaseEventToFields.json
https://tools.hmcts.net/jira/browse/DFR-1093
New event to allow app solicitors to update their organisation in draft case state for consented cases
```
[ ] Yes
[x] No
```
=> DFR-1093: New Event Update Organisation

.github/renovate.json, charts/finrem-ccd-definitions/Chart.yaml
[DFR-1162](https://tools.hmcts.net/jira/browse/DFR-1162)
Enable Renovate for automatic software updates
```
[ ] Yes
[ x] No
```
=> DFR-1162: Enable renovate.json

definitions/contested/json/ComplexTypes/ComplexTypes.json
https://tools.hmcts.net/jira/browse/DFR-932
Fix: Error adding next hearing- dropdown options not available
```
[ ] Yes
[x] No
```
=> DFR-932: Error adding next hearing- dropdown options not available

definitions/contested/json/CaseEvent/CaseEvent.json
https://tools.hmcts.net/jira/browse/DFR-1165
```
[ ] Yes
[ ] No
```
=> DFR-1165: Add ready for hearing event for judge

package.json, yarn.lock
=> Bumping moment to 2.29.4

definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json, definitions/contested/json/CaseTypeTab/CaseTypeTab-DFR-1118-nonprod.json, definitions/contested/json/CaseTypeTab/CaseTypeTab.json
DFR-1118
Restoring old interim hearing event.
```
[ ] Yes
[x] No
```
=> DFR-1118: interim hearing as a collection - v5

charts/finrem-ccd-definitions/Chart.yaml
[DFR-1207](https://tools.hmcts.net/jira/browse/DFR-1207)
Upgrade charts
```
[ ] Yes
[ ] No
```
=> DFR-1207: Upgrade Node chart version

charts/finrem-ccd-definitions/Chart.yaml, charts/finrem-ccd-definitions/values.preview.template.yaml
=> Update CCD chart - Chart.yaml

definitions/consented/json/CaseField/CaseField.json, definitions/contested/json/CaseField/CaseField.json
DFR-1141
Guidance to reflect 16 digit case number
```
[ ] Yes
[x] No
```
=> DFR-1141: Guidance to reflect 16 digit case number

definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState.json
Reverts hmcts/finrem-ccd-definitions#819
=> Revert "DFR-1231 solicitor permission all access"

charts/finrem-ccd-definitions/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/DFR-1251
Fix svc url for gateway
```
[ ] Yes
[x] No
```
=> DFR-1251: preview build

charts/finrem-ccd-definitions/Chart.yaml, charts/finrem-ccd-definitions/values.preview.template.yaml
=> fix preview yml

definitions/consented/json/CaseEventToFields/CaseEventToFields.json
https://tools.hmcts.net/jira/browse/DFR-1079
=> DFR-1079 bugfix appRepresented flag cleared after amend

test/functional/pages/amend-application-details/amend-application-details.js, test/functional/pages/applicant-details/applicant-details.js, test/functional/pages/check-your-answers/check-your-answers.js
Modified three tests
```
[ ] Yes
[X] No
```
=> Nightly dev

definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
https://tools.hmcts.net/jira/browse/DFR-1347
=> DFR-1347 solicitor's shouldn't be able to reject general apps

definitions/consented/json/FixedLists/FixedLists.json
DFR-1206
amend consent order for generated order
```
[ ] Yes
[x] No
```
=> DFR-1206: amend consent order for generated order

definitions/contested/json/CaseEvent/CaseEvent.json
https://tools.hmcts.net/jira/browse/DFR-1213
Add submitted callback
```
[ ] Yes
[x] No
```
=> DFR-1213 - barrister notifications

package.json, yarn.lock
=> Fix minimatch dependency

charts/finrem-ccd-definitions/values.preview.template.yaml, definitions/consented/json/CaseEvent/CaseEvent.json, definitions/contested/json/CaseEvent/CaseEvent.json
https://tools.hmcts.net/jira/browse/DFR-1425
Contested - Issue date should be pre-populated
```
[ ] Yes
[x] No
```
=> DFR-1425: Contested - Issue date should be pre-populated

definitions/contested/json/CaseEventToFields/CaseEventToFields.json
DFR-1678
case number
```
[ ] Yes
[ x] No
```
=> DFR-1678: case number

definitions/contested/json/CaseTypeTab/CaseTypeTab.json
https://tools.hmcts.net/jira/browse/DFR-1719
General Application Directions not showing
```
[ ] Yes
[x] No
```
=> DFR-1719: General Application Directions not showing

Jenkinsfile_CNP
Reverts hmcts/finrem-ccd-definitions#1001
=> Revert "DFR-1078: Tech Debt - Automate Finrem CCD definitions upload via Jenk…"

src/test/java/finrem/HighLevelDataSetupApp.java
=> Enabled AAT ccd def upload

Jenkinsfile_CNP
=> Fixed ccd def generating issue

Jenkinsfile_CNP
Reverts hmcts/finrem-ccd-definitions#1012
=> Revert "Fixed ccd def generating issue"

src/test/java/finrem/HighLevelDataSetupApp.java
Reverts hmcts/finrem-ccd-definitions#1011
=> Revert "Enabled AAT ccd def upload"

charts/finrem-ccd-definitions/Chart.yaml
DFR-1758
update chart version
```
[ ] Yes
[ ] No
```
=> DFR-1758: update chart version

src/test/java/finrem/HighLevelDataSetupApp.java
=> Enable CCD def auto upload on Prod

package.json, test/functional/saucelabs.conf.js, yarn.lock
=> Fixed nightly crossbrowser tests

test/functional/saucelabs.conf.js
=> Fixed file name for nightly crossbrowser tests

charts/finrem-ccd-definitions/values.preview.template.yaml, definitions/contested/json/ComplexTypes/ComplexTypes.json
=> DFR-1791: Contested - on Upload order event drop down is not working

charts/finrem-ccd-definitions/values.preview.template.yaml
=> DFR-1338 removing pr

definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
DFR-1847
Create General Order event visible to others in case history
```
[ ] Yes
[x] No
```
=> DFR-1847: Create General Order event visible to others in case history

definitions/contested/json/CaseEventToFields/CaseEventToFields.json
DFR-1870
refer to judge show field condition -removed special char
```
[ ] Yes
[x] No
```
=> DFR-1870: refer to judge show field condition -removed special char

charts/finrem-ccd-definitions/values.preview.template.yaml, definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/contested/json/CaseEventToFields/CaseEventToFields.json, definitions/contested/json/CaseField/CaseField.json
DFR-1883
Barrister access- Fix FieldShowCondition
```
[ ] Yes
[x] No
```
=> DFR-1883: Barrister access- Fix FieldShowCondition

charts/finrem-ccd-definitions/values.preview.template.yaml
=> DFR-1899: Update cpu/memory

package.json, test/data/ccd-contested-basic-data.json, test/data/verify-contested-tab-data.json, test/functional/codecept.conf.js, test/functional/consented_test.js, test/functional/contested_test.js, test/functional/pages/amend-application-details/amend-application-details.js, test/functional/pages/applicant-details/applicant-details.js, test/functional/pages/case-authorisation/case-authorisation.js, test/functional/pages/caseworker-create/caseworker-create.js, test/functional/pages/divorce-details/divorce-details.js, test/functional/pages/nature-of-application/nature-of-application.js, test/functional/pages/respondent-details/respondent-details.js, test/functional/pages/solicitor-create/solicitor-create.js, test/functional/saucelabs.conf.js, test/helpers/JSWait.js
=> Dfr 1852 fix cb fun tests

package.json
=> Disable accessibility

charts/finrem-ccd-definitions/values.preview.template.yaml, definitions/consented/json/FixedLists/FixedLists.json, definitions/contested/json/FixedLists/FixedLists.json
DFR-1843
fr high court judiciary options list updated
```
[ ] Yes
[x] No
```
=> DFR-1843: fr high court judiciary options list updated

charts/finrem-ccd-definitions/Chart.yaml, charts/finrem-ccd-definitions/values.preview.template.yaml
DFR-1943
Update CCD chart version
```
[ ] Yes
[ ] No
```
=> DFR-1943: Update CCD chart version

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
DFR-1941
Intervener contact details visiable to judge
```
[ ] Yes
[ ] No
```
=> DFR-1941: Intervener contact details visiable to judge

definitions/contested/json/CaseField/CaseField.json
DFR-648
mediation question amendment
```
[ ] Yes
[x] No
```
=> DFR-648: mediation question amendment

charts/finrem-ccd-definitions/values.preview.template.yaml, definitions/contested/json/CaseEvent/CaseEvent.json
DFR-1880
Issue application new pojo, corresponder
```
[ ] Yes
[ ] No
```
=> DFR-1880: Issue application new pojo, corresponder

charts/finrem-ccd-definitions/values.preview.template.yaml, definitions/contested/json/CaseEvent/CaseEvent.json
DFR-1879
Manual Payment Pojo Handler
```
[ ] Yes
[ ] No
```
=> DFR-1879: Manual Payment Pojo Handler

package.json
=> DFR-1798: Temp remove FT

package.json
=> DFR-1798: restore FT

charts/finrem-ccd-definitions/Chart.yaml, charts/finrem-ccd-definitions/values.preview.template.yaml
DFR-1977
Elastic/logstash search fix for preview
```
[ ] Yes
[x] No
```
=> DFR-1977: Elastic/logstash search fix for preview

test/functional/pages/applicant-details/applicant-details.js
=> Check applicant address not confidential

charts/finrem-ccd-definitions/values.preview.template.yaml, definitions/contested/json/CaseEvent/CaseEvent.json
https://tools.hmcts.net/jira/browse/DFR-2004
list for hearing correspondence moved to submit handler
```
[ ] Yes
[x ] No
```
=> DFR 2004 list for hearing correspondence moved to submit handler

charts/finrem-ccd-definitions/values.preview.template.yaml
DFR-2025
send letter feature toggle Test
```
[ ] Yes
[ ] No
```
=> DFR-2025: send letter feature toggle 

charts/finrem-ccd-definitions/values.preview.template.yaml
Preview PR log to AAT AppInsight
Preview PR log to AAT AppInsight
```
[ ] Yes
[ x] No
```
=> Preview PR log to AAT AppInsight

charts/finrem-ccd-definitions/values.preview.template.yaml, test/data/ccd-consented-basic-data.json, test/data/ccd-contested-basic-data.json
DFR-2035
Doucument Id changed
```
[ ] Yes
[ x] No
```
=> DFR-2035: Document Id changed

definitions/consented/json/ChallengeQuestion/ChallengeQuestion.json, definitions/contested/json/ChallengeQuestion/ChallengeQuestion.json
=> DFR-2042: INCIDENT: Incorrect guidance for sols on NOC names

definitions/consented/json/AuthorisationCaseState/AuthorisationCaseState.json
DFR-2060
added system update permission to ready for hearing state
```
[ ] Yes
[ ] No
```
=> DFR-2060: added system update permission to ready for hearing state

package.json, test/functional/smoke_test.js
=> Creating smoke test

bin/run-crossbrowser-tests.sh, test/functional/saucelabs.conf.js, test/functional/smoke_test.js
=> Enabling smoke on XBrowser and fixing reports

charts/finrem-ccd-definitions/values.preview.template.yaml, definitions/contested/json/ComplexTypes/ComplexTypes.json
https://tools.hmcts.net/jira/browse/DFR-2216
=> DFR-2216 adding confidential field to allow compatibility

package.json, test/data/ccd-consented-basic-data.json, test/data/ccd-contested-basic-data.json
=> Updating document url

test/data/ccd-contested-add-intervener.json, test/data/ccd-contested-add-represented-intervener.json, test/data/ccd-contested-consent-order.json, test/data/ccd-contested-general-order.json, test/data/ccd-contested-schedule1-solicitor-create-case.json, test/data/ccd-contested-upload-case-files.json, test/functional/consented_test.js, test/functional/contested_events_test.js, test/functional/steps_file.js
=> Test stability improvements

Jenkinsfile_CNP, test/functional/contested_events_test.js
=> Change properties

test/data/verify-contested-tab-data.json, test/functional/contested_events_test.js, test/functional/interveners_test.js, test/functional/pages/manage-interveners/manage-interveners-add.js, test/functional/pages/tab-data-verification/tab-data-verification.js
=> Testing intervener case access

.github/renovate.json
=> DFR-2049: renovate

charts/finrem-ccd-definitions/values.preview.template.yaml, definitions/consented/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/consented/json/CaseEvent/CaseEvent.json
Dfr 2346 
consent general letter missing respondents name
=> DFR 2346 consent general letter missing respondents name

charts/finrem-ccd-definitions/Chart.yaml, definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
DFR-2137
INC5527559 - Exception record not working as expected
=> DFR-2137: INC5527559 - Exception record not working as expected

Jenkinsfile_nightly, test/functional/pages/create-case-flag/create-case-flag.js
=> Adding playwright install to nightly, and test fix

Jenkinsfile_nightly
=> Increasing test timeout to 3 hours

definitions/contested/json/ComplexTypes/ComplexTypes.json
=> DFR-2379: Apply categorisations to other Consent docs uploaded

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
=> DFR-2476: Added crud permission for other fields to superuser

test/functional/pages/list-for-hearing/list-for-hearing.js, test/functional/steps_file.js
=> Lfh test fix

definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState.json
DFR-2509
update systemupdate state permission
=> DFR-2509: update systemupdate state permission

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField-nonprod.json, definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/contested/json/CaseField/CaseField-nonprod.json, definitions/contested/json/CaseField/CaseField.json, definitions/contested/json/CaseTypeTab/CaseTypeTab-nonprod.json, definitions/contested/json/CaseTypeTab/CaseTypeTab.json, test/unit/definitions/contested/CaseTypeTab.test.js
=> Removal all links to CFV

test/functional/pages/create-case-flag/create-case-flag.js
=> Selecting correct case flag option

definitions/consented/json/CaseEvent/CaseEvent.json, definitions/contested/json/CaseEvent/CaseEvent.json
=> Renmae amend case cron

test/functional/contested_events_test.js, test/functional/contested_schedule1_test.js, test/functional/contested_test.js, test/functional/pages/tab-data-verification/tab-data-verification.js
=> Nightly fix

Jenkinsfile_CNP, charts/finrem-ccd-definitions/Chart.yaml, charts/finrem-ccd-definitions/values.preview.template.yaml, charts/finrem-ccd-definitions/values.yaml
https://tools.hmcts.net/jira/browse/DFR-2579
Create CDAM pod within Preview environment to allow documentsv2 to be viewed
=> Create CDAM pod and link to it

test/functional/pages/check-your-answers/check-your-answers.js, test/functional/pages/contested-pages/mediation-questions.js, test/functional/pages/manage-barrister/manage-barrister.js, test/functional/pages/manage-interveners/manage-interveners-add.js, test/functional/pages/tab-data-verification/tab-data-verification.js
=> Apostrophe test issue

test/functional/admin_test.js, test/functional/consented_caseflag_test.js, test/functional/consented_test.js, test/functional/contested-respondent_test.js, test/functional/contested_caseflag_test.js, test/functional/contested_events_test.js, test/functional/contested_schedule1_test.js, test/functional/contested_test.js, test/functional/general_application_test.js, test/functional/interveners_test.js, test/functional/pages/general-application/general-application.js, test/functional/pages/give-allocation-direction/give-allocation-direction.js, test/functional/pages/list-for-hearing/list-for-hearing.js, test/functional/pages/tab-data-verification/tab-data-verification.js
[DFR-2608](https://tools.hmcts.net/jira/browse/DFR-2608)
=> DFR-2608 Functional tests organisation and fixes

definitions/contested/json/CaseTypeTab/CaseTypeTab.json
DFR-2612
applicant first name in applicant tab
=> DFR-2612: applicant first name in applicant tab

definitions/consented/json/CaseEventToComplexTypes/CaseEventToComplexTypes.json
DFR-1236
After text field optional
=> DFR-1236: After text field optional

definitions/consented/json/CaseEventToComplexTypes/CaseEventToComplexTypes.json
Reverts hmcts/finrem-ccd-definitions#1534
=> Revert "DFR-1236: After text field optional"

definitions/contested/json/CaseTypeTab/CaseTypeTab.json
Reverts hmcts/finrem-ccd-definitions#1533
=> Revert "DFR-2612: applicant first name in applicant tab"

charts/finrem-ccd-definitions/values.preview.template.yaml
=> fix preview chart

definitions/contested/json/CaseField/CaseField.json, test/functional/contested_events_test.js
=> Fix for approvedOrders

README.md
Update PR deployment instructions in README
=> Update PR deployment instructions

charts/finrem-ccd-definitions/values.preview.template.yaml
Remove redundant ccd-case-management-web from preview environment
=> Remove redundant ccd-case-management-web

test/functional/pages/tab-data-verification/tab-data-verification.js
=> Fix failed test for nightly build

charts/finrem-ccd-definitions/values.preview.template.yaml, definitions/contested/json/FixedLists/FixedList-dfr-2159-nonprod.json, definitions/contested/json/FixedLists/FixedLists-prod.json
Reverts hmcts/finrem-ccd-definitions#1570
=> Revert "DFR-2616: Remove redundant Events and Drop Down Options"

charts/finrem-ccd-definitions/values.preview.template.yaml, definitions/contested/json/FixedLists/FixedList-dfr-2159-nonprod.json, definitions/contested/json/FixedLists/FixedLists-prod.json
Reverts hmcts/finrem-ccd-definitions#1599
=> "DFR-2616: Remove redundant Events and Drop Down Options""

definitions/contested/json/FixedLists/FixedList-dfr-2159-nonprod.json, definitions/contested/json/FixedLists/FixedLists-prod.json
=> DFR-2753: FR Restore CaseDocumentType

definitions/contested/json/CaseField/CaseField-nonprod.json, definitions/contested/json/CaseField/CaseField.json
=> Put isCfvCategoriesAppliedFlag to prod

definitions/contested/json/AuthorisationCaseType/AuthorisationCaseType.json
=> Un-shutter Contested cases

definitions/consented/json/ComplexTypes.json, definitions/contested/json/CaseField/CaseField.json, definitions/contested/json/ComplexTypes/ComplexTypes.json
Update the List for Interim Hearing text from 'Please upload any additional documents related to you application'
to 'Please upload any additional documents related to your application'
=> DFR-2649-Update list for interim hearing document prompt

charts/finrem-ccd-definitions/values.preview.template.yaml
=> DFR-2789: preview elastic search -v2

definitions/contested/json/FixedLists/FixedLists-prod.json
Update the fixed list format in prod for Upload Case Files and Manage Case Documents
https://tools.hmcts.net/jira/browse/DFR-2769
=> DFR-2769-Update fixed list format in prod

charts/finrem-ccd-definitions/values.preview.template.yaml, definitions/contested/json/ComplexTypes/ComplexTypes.json
https://tools.hmcts.net/jira/browse/DFR-2809
Rollback change to make parties list always visible in Manage case documents and Manage scaned documents
=> Revert parties visibility change

definitions/contested/json/Categories/Categories.json, src/test/java/finrem/cfv/CategoriesAssignDisplayOrder.java
Reapply changes for:
https://tools.hmcts.net/jira/browse/DFR-2891
https://tools.hmcts.net/jira/browse/DFR-2892
=> DFR-2891-Update reports to expert reports, combine Mortgage capacities and housing particulars

build.gradle
=> Bump ccd-test-definitions

test/functional/pages/manage-interveners/manage-interveners-add.js
Update E2E test data
https://tools.hmcts.net/jira/browse/DFR-2948
Quick fix. Changed the current intervener solicitor email in manage-interveners-add to the newly created intervener solicitor email fr_intervener1_solicitor@mailinator.com.
=> DFR-2948 Update E2E test data

definitions/contested/json/CaseField/CaseField.json, definitions/contested/json/ComplexTypes/ComplexTypes.json
https://tools.hmcts.net/jira/browse/DFR-2919
Add Form G and additional hearing document to Hearing Notices folder
=> Add Form G and additional hearing document to Hearing Notices folder

Jenkinsfile_nightly
=> Update nightly build time

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField-nonprod.json, definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState.json
https://tools.hmcts.net/jira/browse/DFR-2881
I added the caseFileViewComponentLauncher to allow caseworkers and judges to move documents within CFV using the UI, and I have given judges Update Permissions to documents so they can successfully move documents in CFV.
=> DFR-2881 Test Functionality to move documents to different folders in CFV

build.gradle
Remove ccd-test-definitions dependency
=> Remove ccd-test-definitions dependency

test/data/verify-contested-tab-data.json, test/functional/interveners_test.js, test/functional/pages/manage-interveners/manage-interveners-add.js
[2981](https://tools.hmcts.net/jira/browse/DFR-2998)
- Fix nightly build Implement new solicitor1 for Casework add interveners pulled from env vars. 
- Remove unused vars for judge and barrister
=> Fix nightly build Implement new solicitor1 for Casework add interveners

build.gradle
=> Add ccd-test-definitions

definitions/contested/json/FixedLists/FixedLists.json
Temporary fix for MIAM legacy issue: https://tools.hmcts.net/jira/browse/DFR-3003
=> DFR-3003-Temporary fix miam legacy data

definitions/consented/json/CaseTypeTab/CaseTypeTab.json, test/data/ccd-consented-basic-data.json, test/data/ccd-contested-add-intervener.json, test/data/ccd-contested-add-represented-intervener.json, test/data/ccd-contested-basic-data.json, test/data/ccd-contested-consent-order.json, test/data/ccd-contested-general-order.json, test/data/ccd-contested-upload-case-files.json, test/data/ccd-hwf-consented-payment.json, test/data/ccd-hwf-contested-payment.json, test/data/verify-consented-tab-data.json, test/data/verify-contested-tab-data.json, test/functional/consented_caseflag_test.js
Nightly test fix relating to proposed fee update https://tools.hmcts.net/confluence/display/DTSFP/Proposed+Fee+Changes+2024
=> Nighty test fix

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/contested/json/CaseField/CaseField.json
https://tools.hmcts.net/jira/browse/DFR-3032
Add cfvMigrationVersion field to track CFV updates
=> Add cfvMigrationVersion field to track CFV updates

test/functional/contested_test.js
https://tools.hmcts.net/jira/browse/DFR-1688
DFR 1668 introduces test breaking bug, have disabled the failing tests until fix is implemented.
=> Disable failing tests as a result of DFR-1688

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/contested/json/CaseField/CaseField.json
https://tools.hmcts.net/jira/browse/DFR-3032
Add new field to track CFV updates that is searchable
=> Add new field to track CFV updates that is searchable

definitions/consented/json/AuthorisationCaseField/AuthorisationCaseField.json
https://tools.hmcts.net/jira/browse/DFR-3078
Remove solicitor access to case notes
=> DFR-3078 Remove solicitor access to case notes

package.json, yarn.lock
=> Bump braces due to CVE

charts/finrem-ccd-definitions/values.preview.template.yaml, definitions/contested/json/CaseEvent/CaseEvent.json
https://tools.hmcts.net/jira/browse/DFR-3117
- [] tests have been updated / new tests has been added (if needed)
=> DFR-3117 Refactor ConsentOrderApprovedController

test/functional/pages/saving-application-information/saving-application-information.js
https://tools.hmcts.net/jira/browse/DFR-3147
Change the test to check for a specific email address rather than mailto
=> DFR-3147: Change email check

sonar-project.properties, test/functional/pages/notice-of-change/notice-of-change.js
[DFR-3177](https://tools.hmcts.net/jira/browse/DFR-3177)
Add exclusion to sonar cloud to ignore file that fails pipeline. 
[Pipeline](https://build.hmcts.net/view/FinRem/job/HMCTS_d_to_i/job/finrem-ccd-definitions/job/master/846/timestamps/?time=HH:mm:ss&timeZone=GMT+1&appendLog&locale=en)
[Sonarcloud](https://sonarcloud.io/component_measures?id=FrCcdDefinitions&metric=new_coverage)
=> Add to sonar exclusion

definitions/contested/json/CaseTypeTab/CaseTypeTab.json, test/unit/definitions/contested/CaseTypeTab.test.js
https://tools.hmcts.net/jira/browse/DFR-3184
Remove CFV superuser tab as this is no longer required
=> Remove CFV superuser tab

definitions/consented/json/CaseEvent/CaseEvent.json, definitions/contested/json/CaseEventToFields/CaseEventToFields.json
Reverts hmcts/finrem-ccd-definitions#1822
=> Revert "DFR-3063 Upload warnings on upload document "

test/functional/contested_test.js, test/functional/pages/tab-data-verification/tab-data-verification.js
https://tools.hmcts.net/jira/browse/DFR-3201
1. Fix E2E tests that failed due to addition of Case File View tab
2. Include create contested case to preview pipeline tests
=> DFR-3201 Fix E2E tests

default.env
Fix local dev CCD config build
=> Fix local dev CCD config build

test/functional/contested_test.js, test/functional/pages/contested-pages/mediation-questions.js
https://tools.hmcts.net/jira/browse/DFR-3224
Fix ids for MIAM exemption inputs in E2E tests
=> DFR-3222: Fix ids for MIAM exemption inputs

definitions/consented/json/CaseTypeTab/CaseTypeTab.json
https://tools.hmcts.net/jira/browse/DFR-3224
Add scannedD81s to Case View if scannedD81Collection empty
=> Add scannedD81s to Case View if scannedD81Collection empty

package.json, yarn.lock
Fix pipelines
Enforce fast-xml-reader to be above dependent fix ver
=> Fix fast XML vulnerability

definitions/consented/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/consented/json/CaseField/CaseField.json, definitions/consented/json/CaseTypeTab/CaseTypeTab.json
https://tools.hmcts.net/jira/browse/DFR-3228
=> DFR-3228 Odd spacing showing on Fix DFR-3224

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/DFR-3237
Set nightly pipeline to run at 17:45
=> Set nightly pipeline to run at 17:45

charts/finrem-ccd-definitions/values.preview.template.yaml, package.json, src/test/java/finrem/HighLevelDataSetupApp.java, yarn.lock
https://tools.hmcts.net/jira/browse/DFR-3313
1. Increase ccd-definition-store transaction timeout
2. Ignore import failures in preview as the SSLExceptions are (probably) related to timeouts
=> DFR-3313 Increase tx timeout

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField-nonprod.json, definitions/contested/json/CaseEventToFields/CaseEventToFields-nonprod.json, definitions/contested/json/CaseField/CaseField-nonprod.json, definitions/contested/json/CaseTypeTab/CaseTypeTab-nonprod.json, definitions/contested/json/ComplexTypes/ComplexTypes-nonprod.json, definitions/contested/json/FixedLists/FixedLists-nonprod.json
https://tools.hmcts.net/jira/browse/DFR-3321
Create config for Draft orders tab
=> DFR-3321: Draft orders tab

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField-nonprod.json, definitions/contested/json/CaseField/CaseField-nonprod.json, definitions/contested/json/CaseTypeTab/CaseTypeTab-nonprod.json, definitions/contested/json/ComplexTypes/ComplexTypes-nonprod.json
https://tools.hmcts.net/jira/browse/DFR-3304
Add draft orders to Case Documents
=> Add draft orders to Case Documents

definitions/contested/json/CaseEvent/CaseEvent-nonprod.json
DFR-3304: Add Upload draft orders submitted handler
=> DFR-3304: Add Upload draft orders submitted handler

definitions/contested/json/CaseEventToComplexTypes/FR_draftOrdersTouploadAgreedDraftOrder-nonprod.json, definitions/contested/json/CaseEventToFields/CaseEventToFields-nonprod.json, definitions/contested/json/ComplexTypes/FR_AgreedDraftOrders_nonprod.json, definitions/contested/json/ComplexTypes/FR_AgreedPensionSharingAnnexes-nonprod.json, definitions/contested/json/ComplexTypes/FR_uploadAgreedDraftOrder-nonprod.json, definitions/contested/json/FixedLists/FR_fl_AgreedDraftOrderResubmission-nonprod.json
See [DFR-3388](https://tools.hmcts.net/jira/browse/DFR-3388)
Upload Agreed Draft Order page.
=> DFR-3388(DFR-3319-1) Upload Agreed Draft Order Page

definitions/contested/json/CaseEventToFields/CaseEventToFields-nonprod.json
See [DFR-3319](https://tools.hmcts.net/jira/browse/DFR-3319)
=> DFR-3319 Mid event to ensure Non-Word documents

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField-nonprod.json, definitions/contested/json/CaseEventToFields/CaseEventToFields-nonprod.json, definitions/contested/json/CaseField/CaseField-nonprod.json
See [DFR-3303](https://tools.hmcts.net/jira/browse/DFR-3303)
Add guidance in the new draft order first page.
=> DFR-3303 CT: Select event paragraph

Jenkinsfile_nightly
Reverts hmcts/finrem-ccd-definitions#2087
=> Revert "DFR 3232 Nightly test results"

package.json, yarn.lock
This is a CVE fix
Update dependency eslint to v9.15.0
and fix @eslint/plugin-kit and cross-spawn
=> Update dependency eslint to v9.15.0

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/VUL-6406
Update dependencies to address ITHC report
=> VUL-6406: Update vulnerable dependencies

definitions/contested/json/CaseEventToComplexTypes/DFR-3332-1-nonprod.json, definitions/contested/json/CaseEventToComplexTypes/DFR-3332-2-nonprod.json, definitions/contested/json/CaseEventToComplexTypes/DFR-3332-3-nonprod.json, definitions/contested/json/CaseEventToComplexTypes/DFR-3332-4-nonprod.json, definitions/contested/json/CaseEventToComplexTypes/DFR-3332-5-nonprod.json, definitions/contested/json/ComplexTypes/DFR-3332-nonprod.json
See [DFR-3494](https://tools.hmcts.net/jira/browse/DFR-3494)
=> DFR-3494 Add hearing judge to Approve Orders Page.

definitions/contested/json/CaseEventToFields/DraftOrders-nonprod.json, definitions/contested/json/CaseField/DraftOrders-nonprod.json
https://tools.hmcts.net/jira/browse/DFR-3391
Update Upload draft orders page headings
=> DFR-3391: Update Upload draft orders page headings

sonar-project.properties
DFR-3429
Sonar exclusion to deploy refuge
=> DFR-3429: Add sonar exclusions

definitions/contested/json/AuthorisationCaseField/DFR-3495-nonprod.json, definitions/contested/json/CaseEventToComplexTypes/DFR-3495-0-nonprod.json, definitions/contested/json/CaseEventToFields/DFR-3495-nonprod.json, definitions/contested/json/CaseField/DFR-3495-nonprod.json, definitions/contested/json/ComplexTypes/DFR-3495-nonprod.json
See [DFR-3529](https://tools.hmcts.net/jira/browse/DFR-3529)
=> DFR-3529 Rename to extraReportFieldsInput

definitions/contested/json/CaseEventToComplexTypes/CaseEventToComplexTypes-prod.json, definitions/contested/json/CaseEventToComplexTypes/CaseEventToComplexTypes.json, definitions/contested/json/CaseEventToFields/CaseEventToFields.json, yarn.lock
=> DFR-3543 merge

README.md
https://tools.hmcts.net/jira/browse/DFR-3517
Update readme for FixedList judge data
=> DFR-3517: Update readme for FixedList judge data

definitions/contested/json/CaseField/ExpressPilot-nonprod.json
DFR-3596
Corrected a field so that it's a label not text
Import script
=> DFR-3596: Fix to switch from text to label

charts/finrem-ccd-definitions/Chart.yaml
https://tools.hmcts.net/jira/browse/DFR-3624
Update nodejs chart to use oci version
=> DFR-3624: Update nodejs chart

playwright-e2e/pages/events/create-case/RespondentRepresentedPage.ts
Add rSolRefernce field population to respondent solicitor page population.
=> Update RespondentRepresentedPage to populate solictor ref

playwright-e2e/pages/CaseDetailsPage.ts, playwright-e2e/pages/ManageOrgDashboardPage.ts
=> playwright test fix

playwright-e2e/pages/CaseDetailsPage.ts, playwright.config.ts
1. The value 180_00 looks like a mistyped number. I assume it is 3 minutes.
=> Nightly fix typo

playwright-e2e/functional/contested/assign_respondent_case.spec.ts, playwright-e2e/pages/CaseDetailsPage.ts
=> Nightly build fix.

playwright-e2e/functional/contested/assign_respondent_case.spec.ts
=> Add missing await

Jenkinsfile_CNP, Jenkinsfile_nightly
=> Missing secret configuration

definitions/contested/json/CaseEventToFields/CaseEventToFields.json
https://tools.hmcts.net/jira/browse/DFR-3669
Revert change from DFR-3607 as it prevents judge Approve orders event from submitting
=> DFR-3669: Revert change from DFR-3607

test/functional/pages/create-case-flag/create-case-flag.js, test/functional/pages/manage-flags/manage-case-flags.js
See [DFR-3676](https://tools.hmcts.net/jira/browse/DFR-3676)
Fix for Case Flag functional tests
=> Case Flag Nightly fix

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/DFR-3664
Add new judge name secret to CCD configuration build pipeline
=> DFR-3664: Add new judge secret

definitions/contested/json/AuthorisationCaseField/ExpressPilot-nonprod.json
See [DFR-3671](https://tools.hmcts.net/jira/browse/DFR-3671)
=> DFR-3671 Missing AuthorisationCaseField

charts/finrem-ccd-definitions/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/DFR-3698
Enable send letter duplicate check in preview
=> DFR-3698: Enable send letter duplicate check in preview

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
See [DFR-3714](https://tools.hmcts.net/jira/browse/DFR-3714)
Add Auth for sys user on confidential bulk print fields for migration.
=> DFR-3714 interim hearing migration

playwright-e2e/functional/contested/create_case/create_case.spec.ts, playwright.config.ts
Fix nightly test failure after CW peromission corrected - case must be submitted to view.
=> fix CW view created case, fix line output in CI

build.gradle
See [DFR-3780](https://tools.hmcts.net/jira/browse/DFR-3780)
=> DFR-3780 Remove Jitpack dependency

definitions/consented/json/CaseEvent/CaseEvent.json
See [DFR-3791](https://tools.hmcts.net/jira/browse/DFR-3791)
=> DFR-3791 CS: Paper case Send Order fails if case has no court

playwright-e2e/config/case-data.ts, playwright-e2e/functional/consented/case_flag_tests.spec.ts, playwright-e2e/functional/contested/case_flag/case_flag_tests.spec.ts, test/functional/consented_caseflag_test.js
See [DFR-3807](https://tools.hmcts.net/jira/browse/DFR-3807)
Added below playwright tests:
- Consented - Judge manage case flag
- Contested - Caseworker creates case flag
Skipped codecept tests:
- Consented - Judge manage case flag
=> DFR-3807 Consent Judge manage flag and contest create flag

Jenkinsfile_nightly
Change Nightlies to run at 18:00PM
=> Change Nightlies to run at 18:00PM

package.json, yarn.lock
=> Fix CVE brace-expansion

Jenkinsfile_nightly, package.json, playwright.config.ts, yarn.lock
See [DFR-3853](https://tools.hmcts.net/jira/browse/DFR-3853)
Enabled PW report
used PW common library for recommended and Projects config
Sample report in [nightly-dev](https://build.hmcts.net/job/HMCTS_d_to_i_Nightly/job/finrem-ccd-definitions/job/nightly-dev/28/FunctionalTestReport/)
=> DFR-3853 Enable PW reporting feature

.github/renovate.json
N/A
Renovate automerge set as "after 7am and before 9am every weekday"
This is the same as COS, and no issues with the times there.
=> automerge after 7am and before 9am every weekday

playwright-e2e/pages/CaseListPage.ts
See [DFR-3893](https://tools.hmcts.net/jira/browse/DFR-3893)
Quick fix on nightly test failures. 
Changed expectation of Jurisdiction and Case type field, as AAT has more than which i tested in local
=> Quick fix for nightly failures on expectation

Jenkinsfile_nightly
Configured jenkins nightly pipeline to take tags as parameter to run targeted as needed.
successful pipeline - https://build.hmcts.net/job/HMCTS_d_to_i_Nightly/job/finrem-ccd-definitions/job/nightly-dev/12/
=> Configure jenkins pipeline to configure build parameter

package.json, yarn-audit-known-issues, yarn.lock
=> Fix on-headers CVE

package.json, yarn.lock
set yarn version to stable latest one
=> Fix yarn version upgrade failure in nightly pipeline

playwright-e2e/pages/CaseDetailsPage.ts
Fix on casedetailspage.ts tab locator to locate the first element in the index to avoid strict playwright violation error.
=> Fix Nightly test failures

playwright-e2e/fixtures/axe-fixture.ts, playwright-e2e/fixtures/utils/axe-utils.ts, playwright-e2e/test/consented/approve_application.spec.ts, playwright-e2e/test/consented/create_case.spec.ts, playwright-e2e/test/consented/update_contact_details.spec.ts, playwright-e2e/test/contested/FR_CreateCases/create_case.spec.ts, playwright-e2e/test/contested/FR_CreateCases/create_express_case.spec.ts, playwright-e2e/test/contested/FR_GeneralApplicationDirections/general_application_directions.spec.ts, playwright-e2e/test/contested/FR_ManageHearings/manage_hearings.spec.ts, playwright-e2e/test/contested/FR_SendOrderToApplicantSolicitor/send_order_applicant_solicitor.spec.ts, playwright-e2e/test/contested/FR_UploadDraftOrder/upload_draft_order.spec.ts, playwright-e2e/test/contested/FR_addSchedulingListingInfo/list_for_hearing_express_case.spec.ts, playwright-e2e/test/contested/FR_amendApplication/amend_form_a_application_details_standard_case.spec.ts, playwright-e2e/test/contested/FR_consentOrder/consent_in_contested_case.spec.ts, playwright-e2e/test/contested/FR_directionOrder/process-order.spec.ts, playwright-e2e/test/contested/FR_generalApplication/general_application_e2e.spec.ts, playwright-e2e/test/contested/FR_giveAllocationDirections/give_allocation_direction.spec.ts, playwright-e2e/test/contested/FR_giveAllocationDirections/give_allocation_direction_express_case.spec.ts, playwright-e2e/test/contested/FR_listForInterimHearing/list_for_interim.hearing.spec.ts, playwright-e2e/test/contested/FR_manageBarrister/manage_barrister.spec.ts, playwright-e2e/test/contested/FR_manageCaseDocuments/manage_case_documents.spec.ts, playwright-e2e/test/contested/FR_manageExpressCase/manage_express_case.spec.ts, playwright-e2e/test/contested/FR_manageInterverners/manage_interveners.spec.ts, playwright-e2e/test/contested/FR_sendOrder/send_order.spec.ts
Refactored report generation part to fixtures so that it will happen automatically after each test if any axe audit is conducted.
Moved report generation to Axe-fixtures so that it will execute after each test, thereby reduce user mistake of miss calling report generation.
Even though this is called after each test, report will not be generated unless page is analysed for accessibility report.
=> Refactored generate report to Axe fixtures

playwright-e2e/fixtures/utils/axe-utils.ts
There is a issue where when multiple reports are added to consolidated Axe report, some sections are not expandable due to duplicate id's in report.
This PR fixes that issue for report generation
=> Fix Accessibility report Not expanding subsections in report

playwright-e2e/pages/events/process-order/ProcessOrderHearingDetailsPage.ts
=> Add missing rename processOrderAddHearing -> isAddHearingChosen

Jenkinsfile_nightly, playwright-e2e/config/config.ts, playwright-e2e/data-utils/api/TokenHelperApi.ts, playwright-e2e/fixtures/create-fixture.ts, playwright-e2e/pages/NoticeOfChangePage.ts, playwright-e2e/test/common-tests/notice_of_change.spec.ts
See [DFR-4047](https://tools.hmcts.net/jira/browse/DFR-4047)
Added tests for NOC for a case.
Added new test users, 
added user cred secrets in vault, 
updated jenkins nightly with required secrets
One test is skipped as defect DFR-4058 is raised.
=> DFR-4047 PW test for Notice of Change scenario

playwright-e2e/test/contested/FR_addSchedulingListingInfo/list_for_hearing_shows_hearing_tab.spec.ts
List for hearing not available in 'Prepare for hearing' so refactoring 'List for hearing information shows on new hearings tab after any manage hearings event' test to perform List for Hearing event before Manage Hearings.
See [DFR-4004](https://tools.hmcts.net/jira/browse/DFR-4004)
=> Fix PW test which is failing due to Manage Hearing state change

playwright-e2e/config/config.ts, playwright-e2e/fixtures/utils/axe-utils.ts
As case locked banner can happen on any page, add this exclusion in global setting, so that this element is excluded from audit.
=> excluding elements that are known issues

definitions/contested/json/AuthorisationCaseEvent/GeneralApplicationDirectionsMH-nonprod.json, definitions/contested/json/AuthorisationCaseEvent/ManageHearings-nonprod.json
- Add missing Migration User, Judiciary and Solicitor auth for MH events. 
=> Add missing Auth for MH events

playwright-e2e/test/contested/FR_amendApplication/amend_form_a_application_details_standard_case.spec.ts
See [DFR-4130](https://tools.hmcts.net/jira/browse/DFR-4130)
Flaky PW test causing failures, will investigate and fix but skipping for now as test is consistently failing
Working manually on AAT
=> skip flaky PW test

definitions/contested/json/ComplexTypes/ComplexTypes.json
See [DFR-4136](https://tools.hmcts.net/jira/browse/DFR-4136)
- Add `cleveland` court fiexed list to FR_ct_courtList account for typo `cleavelandCourtList`. 
- Manual
=> DFR-4136  Account for cleveland typo

playwright-e2e/pages/events/create-general-email/CreateGeneralEmailPage.ts, playwright-e2e/resources/check_your_answer_content/create_general_email/createGeneralEmailTable.ts, playwright-e2e/resources/tab_content/consented/case_documents_tab.ts, playwright-e2e/resources/tab_content/contested/case_documents_tab.ts, playwright-e2e/test/common-tests/create_general_email.spec.ts, playwright-e2e/test/contested/FR_judgeDraftDirectionOrder/judge_upload_approved_order.spec.ts
See [DFR-4155](https://tools.hmcts.net/jira/browse/DFR-4155)
- Ignored Axe-Core accessibility violation which will stop failed test flagging on Nigtly (bug ticket already raised DFR-4155).
- Updated Create general email tests to use fr_respondent_solicitor1@mailinator.com so emails can be validated in the inbox.
- Added a method to verify invalid email addresses are not accepted.
Notes
- Accessibility ignore violation is temporary and will be revisited once DFR-4155 is fixed.
=> Playwright ignore accessibility violation and add checks for email tests

playwright-e2e/data-utils/test_data/EnvTestDataConfig.ts
- Replace deleted static docs used in API calls with new docs post clean up. 
=> Replace static docs used in API calls with new ones post doc clean up

.github/workflows/create-preview-environment.yml
Fix GitHub Action preview links formatting
=> Fix GitHub Action preview links formatting

README.md
Update readme with instructions on Create preview environment action
=> Update readme with instructions on Create preview environment action
