hmcts/finrem-ccd-definitions

definitions/consented/json/CaseEvent.json

Added callback URLs to all 'assign to judge' events to trigger BE logic for BSP-287:
https://tools.hmcts.net/jira/browse/BSP-287
Added 'newPaperCase' to prestate of 'FR_HWFDecisionMade' event for BSP-289:
https://tools.hmcts.net/jira/browse/BSP-289

BSP-287 & BSP-289: Add callbacks for 'assign to judge' event and new prestate for FR_HWFDecisionMade

---

definitions/consented/json/CaseEventToFields/CaseEventToFields.json
definitions/consented/json/FixedLists/FixedLists.json

https://tools.hmcts.net/jira/browse/FR-1696
Remove extra space from 'Property Adjustment Order' in prep for database change
```
[x] Yes
[ ] No
```

Remove extra space from 'Property Adjustment Order'

---

definitions/consented/json/CaseEventToFields/CaseEventToFields.json
definitions/consented/json/ComplexTypes.json
definitions/consented/json/FixedLists/FixedLists.json

https://tools.hmcts.net/jira/browse/FR-1725
Hiding the child gender field (populated through BSP if the value is 'not given' aka - not Male or Female
```
[ ] Yes
[x] No
```

FR-1725 - adding hide for child gender if its not set

---

definitions/consented/json/CaseEvent.json
definitions/contested/json/CaseEvent/CaseEvent.json

https://tools.hmcts.net/jira/browse/FR-1470
- Contested Order Not Approved Implemented
- Refactored 'order not approved' endpoint for use across both consented and contested
```
[x] Yes
[ ] No
```

FR-1470: Adding Contested Not Approved Notification

---

definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState.json
definitions/contested/json/CaseEvent/CaseEvent.json
definitions/contested/json/CaseTypeTab/CaseTypeTab-nonprod.json
definitions/contested/json/State/State.json

https://tools.hmcts.net/jira/browse/FR-1746
Created new "Assign to Judge (consent)" event that moves case from 'consentedOrderSubmitted' state to new 'awaitingJudiciaryResponseConsent' state.
This can only be triggered by the court admins.
No need to explicitly toggle this change as the event can only be called from prestate 'consentedOrderSubmitted' which is toggled off already - therefore unable to get into required prestate on Production

Added Awaiting Judiciary Response (consent) state and event

---

definitions/consented/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
definitions/consented/json/AuthorisationCaseField/AuthorisationCaseField.json
definitions/consented/json/AuthorisationCaseState/AuthorisationCaseState.json
definitions/consented/json/AuthorisationCaseType/AuthorisationCaseType.json
definitions/consented/json/CaseEvent/CaseEvent.json
definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent-consentedInContested-nonprod.json
definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent-consentedInContested-prod.json
definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent-generalApplication-nonprod.json
definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField-nonprod.json
definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState.json
definitions/contested/json/AuthorisationCaseType/AuthorisationCaseType.json

- Deleted redundant 'FR_dataMigration' event (not to be confused with actual FR_migrateCase event we call from COS for migrations)
- Deleted ALL references of 'D' from all CRUD permissions as delete is not offered by CCD whatsoever
- Deleted "U" from all AuthorisationCaseEvent.json CRUD permissions - 'U' is not used for AuthorisationCaseEvent (see here: https://tools.hmcts.net/confluence/display/RCCD/CCD+Definition+Glossary+for+Setting+up+a+Service+in+CCD#CCDDefinitionGlossaryforSettingupaServiceinCCD-ccdDefTabCaseEvent)

Cleaned up and removed redundant config

---

package.json

fixes CVE issue that breaks build pipeline
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ ini                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >1.3.6                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ codeceptjs                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ …

RPET-164 fix CVE 1589 Prototype Pollution on ini package

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/RPET-680
To add new judges to the system, we need to add a new secret to the existing list of secrets. 
The following code enables the Jenkins pipeline to make use of the new Key and add the judges defined in secrets to the config file.
```
[ ] Yes
[X] No
```

RPET-680 Update jenkins pipeline to handle new judge secrets

---

definitions/contested/json/CaseTypeTab/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/RPET-582
When users selected "No" from the `addToComplexityListOfCourts` Options
The field show condition was incorrect for this field, it has now been updated to point to the correct value that is stored by the fixed list: 
```  
"LiveFrom": "01/01/2017",
"ID": "FR_complexityList",
"ListElementCode": "falseNo",
"ListElement": "No"
```
```
[ ] Yes
[x] No
```

RPET-582- Updating Logic for complexity field to correct value

---

definitions/contested/json/CaseEventToFields/CaseEventToFields.json

Logic does not make sense, regionList "northEast" & NorthWest = "cleaveland"
Cleaveland is under a NorthEast court, logic updated to reflect this
```
[ ] Yes
[x] No
```

Updating to NorthEast, as this FRC is NE not NW

---

Jenkinsfile_CNP
README.md
charts/finrem-ccd-definitions/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/DFR-2968
Enable preview environment builds to set finrem-cos image using GitHub label

Enable preview environment builds to set finrem-cos image using GitHub label

---

package.json
yarn.lock

Bump azure identity due to CVE.
This dependency is from  "@hmcts/properties-volume": "1.1.0",

Bump azure identity due to CVE

---

definitions/contested/json/CaseEventToFields/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/DFR-3478
Remove hidden (and unneeded) field that is no longer used in the Upload Approved Order event.

DFR-3478: Prevent duplication of additional documents

---

definitions/contested/json/AuthorisationCaseField/DraftOrders-nonprod.json
definitions/contested/json/CaseEventToFields/DraftOrders-nonprod.json
definitions/contested/json/CaseField/DraftOrders-nonprod.json

https://tools.hmcts.net/jira/browse/DFR-3487
Remove link to consent order event for intervenevers.
As the link is still required for other users the text shown on screen is now created in Java code and displayed using field interpolation

DFR-3487: Draft orders - remove consent order link for interveners

---

playwright-e2e/functional/consented/create_case.spec.ts

DFR-3596
Earlier DFR-3596 change refactored how local court dropdowns were selected by Playwright testing. I amended and locally tested for all contested cases.  Didn't change for consented.  Issue picked up in the Nightly run.
Local running.
Manually checked that all calls to selectCourtZoneDropDown included a valid court param.
-->

DFR-3596: Fixed local court initialisation in Playwright test

---

definitions/contested/json/CaseEventToFields/CaseEventToFields.json
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/DFR-3623
Reverting what was merged with https://github.com/hmcts/finrem-ccd-definitions/pull/2370
Pointing the court selection page at the old controller method, until it's new handler replacement includes validation to stop High Court or Royal Court of Justice being chosen from the court selection screen.
The old controller method is still there, as it's still used by other contested events.
Updated Playwright tests will still pass, they make sure the court info shows - which it does.
Manually tested in Preview.  Have confirmed that the validation is restored and that the selected court fields are still being set.

DFR-3623: 

---

definitions/contested/json/CaseTypeTab/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/DFR-3677
Fix for https://tools.hmcts.net/jira/browse/DFR-3550 only works with newly uploaded draft orders.
Cases with existing draft orders no longer show the Draft orders tab.
Change the tab show condition to handle cases with no value set for isUnreviewedDocumentPresent

DFR-3677: Change Draft orders tab show condition to handle existing cases

---

definitions/contested/json/AuthorisationCaseField/ExpressPilot-nonprod.json
definitions/contested/json/CaseEventToFields/CaseEventToFields-newPaperCase.json

**Express Pilot**
https://tools.hmcts.net/jira/browse/DFR-3644
https://tools.hmcts.net/jira/browse/DFR-3645
**Variation Order bug**
https://tools.hmcts.net/jira/browse/DFR-3689
**Express Pilot**
Auth fix so that the Caseworker running the amend paper case event can see Express Pilot labels.  There were no issues running locally or in Preview.  But the issue was recreatable in AAT.
**Variation Order bug**
During earlier testing of the same amend paper case event, this bug was spotted when variation order dependent labels were alone on a page with no page show condition.  This meant that nothing appeared on this page when the variation order was missing.
Copied how Create paper case does it, and moved  fields (by one position) to the related page. Means no empty page shows, the variation …

DFR-3644-3645 follow up auth fix so that labels show in AAT

---

definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/DFR-3670
Add access to field latestDraftHearingOrder for role caseworker-divoce-systemupdate
The lack of access to this field is causing errors during cron job execution if the field is present on a case being updated

DFR-3670: Add access to field latestDraftHearingOrder for system update role

---

playwright-e2e/pages/CaseDetailsPage.ts

Quick fix for nightly failulres in case flag cases.
changed the logic to iterate only for visible elements.
case flag page have multiple DOM elements with hidden state for same String/text we try to find.

quick fix for nightly assert tab failures in case flag tests

---

definitions/contested/json/CaseEventToFields/CaseEventToFields-newPaperCase.json
playwright-e2e/resources/check_your_answer_content/create_case/createCaseTable.ts
playwright-e2e/test/contested/FR_CreateCases/create_express_papercase.spec.ts
playwright-e2e/test/contested/FR_CreateCases/create_papercase.spec.ts

https://tools.hmcts.net/jira/browse/DFR-3934
The Upload other documents field appears on the wrong page for the New Paper Case event.
Fix pageId for FR_newPaperCase upload additional document field
**Added Playwright changes to test upload function of the Additional Doc upload field

Fix pageId for FR_newPaperCase upload other document field
